name = "AirHockey"
uuid = "2e594433-6dd6-493d-8cab-c702511b3cc4"
authors = ["Emil <emil.zychowicz@gmail.com>"]
version = "0.1.0"

[deps]
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
